### ISSUE TITLE
Download Issues

### ISSUE THREAD

**Issue by krash1220** [datashaman/putio-automator#10]
Everything was working fine with docker until this last update. Now the downloader starts but some files end up being 0 bytes and the downloader keeps running but the file never finishes. I have to go in and delete the file and restart the downloader. It works fine for a few files and then it does it randomly again and again. Before I had it running all the time and it downloaded everything just fine. Now I have to constantly check to see if it's running correctly. Plus, there needs to be a way to get around the permission issues because Sickrage  can't process the files. I have to run a script every 10 or 15 minutes changing permissions on the downloads folder so Sickrage will process the files.

And sometimes the downloader doesn't move the files from the incomplete folder to the downloads folder and I have to do it manually. And sometimes not all the files are downloaded from putio and I have to delete them manually as well.

s there a way to go back to the 1.0.1 docker image?

**Comment by krash1220** [comment]
Okay, this time I didn't delete the 0 byte file but just restarted the downloader and it starts downloading the file and continues but I still can't figure out why it starts then stops at 0 bytes. This is driving me crazy.

**Comment by datashaman** [comment]
Hmm, not sure why that could be happening. There is a release_1.0.0 docker image which you could pull: `docker pull datashaman/putio-automator:release_1.0.0`. Make sure your installed package is the same version other wise bad things could happen. Any logs that might be useful from inside the docker container?

**Comment by datashaman** [comment]
It sounds like a permissions issue, something is setting the permissions to something else. Do you have any other processes running on things in that folder?

**Comment by krash1220** [comment]
It's not permissions. To make sure I created an Incomplete folder under /Incomplete which is owned by root. Changed the config file. The first file downloaded just fine and was moved to Complete folder. The second file started downloading stopped at 0 bytes. Downloader continues to run but does nothing.

**Comment by krash1220** [comment]
Is there a way to make the downloader download as a user?

**Comment by krash1220** [comment]
Oh, and I wanted to tell you the groomer keeps giving a fatal Exited too quickly (process log may have details). I don't ever start or stop that one. But for some reason it keeps doing that.

**Comment by krash1220** [comment]
Any logs that might be useful from inside the docker container? How do I find the logs from docker container? Where are the docker containers stored?

**Comment by krash1220** [comment]
I tried to install pip install --user putio-automator==1.0.0 then docker pull datashaman/putio-automator:release_1.0.0 when I run putio docker run -s 0 -e 0 docker starts pulling the latest version. How do I start the 1.0.0 image?

**Comment by krash1220** [comment]
I think I might have found the problem. Remember I said I made a /Incomplete folder that was owned by root. When the downloader starts it changes the permissions to root. Well, I got to thinking and I remember a while back that I thought the owner of the folder was suppose to be www-data. That's why I made the /Incomplete folder owned by root. So, I changed permissions for the /Incomplete folder to www-data, the first file downloads but the second won't, and when the downloader starts the file permissions are once again changed to root. Could that be the problem?

**Comment by datashaman** [comment]
You can specify a tag option (-t i think) for the specific docker tag you want to use: -t datashaman/putio-automator:release_1.0.0

**Comment by datashaman** [comment]
I'll only be able to look at the issue this weekend, *very* busy with the paying job at the moment. Try running docker as the same user www-data? You'll have to add www-data to the docker group to allow that I think. We'll come up with a better solution, that might make it work in the meantime.

**Comment by krash1220** [comment]
Okay, thanks. I'll muddle through until you have time. I completely understand a paying job always comes first.

**Comment by krash1220** [comment]
I think I got it fixed. I'm not completely sure but I think it worked after I added krash to the www-data group and added www-data to my krash group. So when the files download the folder permissions are owner root and group krash and everything seems to be okay. I still have to cron a script for changing permissions after the files are moved to the downloads folder but I can live with that.

**Comment by datashaman** [comment]
Hi, glad to hear you've managed to sort something out, sorry. Still stuck in paying work right now, busy with a site deployment that is taking a while... :(
