### ISSUE TITLE
Docker run : "exec user process caused "exec format error"

### ISSUE THREAD

**Issue by jornetsimon** [datashaman/putio-automator#24]
`putio docker run`
>`standard_init_linux.go:190: exec user process caused "exec format error"`

And then terminates.

I'm on 1.0.2. Freshly installed.
Raspbian Stretch

**Comment by bpgregson** [comment]
I'm experiencing the same problem.  I suspect the issue has to do with the image architecture.  ARM cannot run x86_64 images.  Does that mean the putio binary needs an ARM compatible binary?

**Comment by bpgregson** [comment]
I resolved this error by building the docker image locally.  Note, I'm running [osmc](https://osmc.tv/about/) on a [Vero 4K](https://osmc.tv/vero/) but should be similar for Raspberry Pi.

I first removed the original putio-automator container (not sure if this was necessary)
```
osmc@osmc-turtle:~$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                     PORTS               NAMES
54455d869108        datashaman/putio-automator   "putio docker boot..."   8 minutes ago       Exited (1) 8 minutes ago                       trusting_bohr
osmc@osmc-turtle:~$ docker rm trusting_bohr
trusting_bohr
```
and the image.
```
osmc@osmc-turtle:~$ docker images -a
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
datashaman/putio-automator   latest              6b107cb9c78a        7 months ago        202MB
osmc@osmc-turtle:~$ docker rmi datashaman/putio-automator
```
I cloned the repo
```
osmc@osmc-turtle:~$ git clone https://github.com/datashaman/putio-automator.git
Cloning into 'putio-automator'...
remote: Enumerating objects: 840, done.
remote: Total 840 (delta 0), reused 0 (delta 0), pack-reused 840
Receiving objects: 100% (840/840), 105.71 KiB | 0 bytes/s, done.
Resolving deltas: 100% (548/548), done.
```
then changed to putio-automator top-level directory and built the image. (Note the trailing '.' in the 'docker build' command.)
```
osmc@osmc-turtle:~$ cd putio-automator/
osmc@osmc-turtle:~/putio-automator$ docker build -t datashaman/putio-automator .
```
When the build completed, success messages were returned.
```
Sending build context to Docker daemon  251.4kB
...
Successfully built 8ce69373d996
Successfully tagged datashaman/putio-automator:latest
```
Finally, I was able to successfully run the container via the putio script and monitor the status at [localhost:9001](url)
```
osmc@osmc-turtle:~/putio-automator$ cd
osmc@osmc-turtle:~$ putio docker run
```
