### ISSUE TITLE
Clarify usage for files list attributes

### ISSUE THREAD

**Issue by bpgregson** [datashaman/putio-automator#25]
When I enter the command
`me@me:~$ putio files list -p folder-in-putio`
The following error is returned:
```
usage: Manage torrents and downloads on Put.io
putio: error: too many arguments

```
Could you kindly clarify and/or provide an example for the correct usage of `-p PARENT_ID` when listing files in a putio folder that is a child folder to the top level account folder?

Much thanks!

**Comment by datashaman** [comment]
You need to use the numeric ID for the folder, which can be found in the URL on put.io.

The default root folder is ID 0. Folders are identified by numbers like 56834550.
