### ISSUE TITLE
Could not fetch URL - SSL Error

### ISSUE THREAD

**Issue by dannyvfilms** [datashaman/putio-automator#26]
![screen shot 2019-02-20 at 1 02 46 pm](https://user-images.githubusercontent.com/44555970/53117170-ebe5d380-350f-11e9-8a97-13f09bd2d34f.png)

Couldn't get past the first step of installation on MacOS 10.14.3

Daniels-MacBook-Pro:~ dannyvfilms$ pip install --user putio-automator
Collecting putio-automator
  Could not fetch URL https://pypi.python.org/simple/putio-automator/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement putio-automator (from versions: )
No matching distribution found for putio-automator
Daniels-MacBook-Pro:~ dannyvfilms$

**Comment by datashaman** [comment]
Have a look here for a solution, I think: https://stackoverflow.com/a/38908406/401467
