### ISSUE TITLE
No module named putio

### ISSUE THREAD

**Issue by krash1220** [datashaman/putio-automator#4]
I did a clean install. Installed everything like I always do. I'm using Linux Mint 18.1. Don't know if they changed something in python or something else but no matter what I do I keep getting the same error message.

command 
python /TV/Putio-Automator/manage.py files_download

error
Traceback (most recent call last):
  File "/TV/Putio-Automator/manage.py", line 8, in <module>
    import putio
ImportError: No module named putio

**Comment by datashaman** [comment]
- did you run mkvirtualenv with virtualenvwrapper?
- are you in the virtualenv?
- which version of python did you use? run: `python --version` and post it here.
- when you're in the virtualenv, run: `pip install yolk; yolk -l` and post it here.

**Comment by datashaman** [comment]
Argh, never mind. I see the problem now. Put.IO have changed the name of the Python package. Must be a breaking change that needs attention. I'll let you know once I've solved the issue.

**Comment by datashaman** [comment]
Thanks for the report, I would not have picked this up for a while yet. The latest release fixes this issue. I suggest forcing an upgrade of all installed packages so you get the latest version of `putiopy` package, but it will work regardless if you don't.

    pip install --upgrade --force-reinstall -r requirements.txt

**Comment by datashaman** [comment]
I'm leaving this open for a while so other users can see it and fix if needed.

**Comment by krash1220** [comment]
Fixed, thank you so much.
