### ISSUE TITLE
torrents_watch putiopy ClientError

### ISSUE THREAD

**Issue by krash1220** [datashaman/putio-automator#5]
files_download from Put.io works fine but torrents_watch gives me these errors
I did the pip install --upgrade --force-reinstall -r requirements.txt just in case but that didn't work either.

Traceback (most recent call last):
  File "/TV/Putio-Automator/manage.py", line 214, in <module>
    manager.run()
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/home/krash/.local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/TV/Putio-Automator/manage.py", line 125, in torrents_watch
    torrents_add()
  File "/TV/Putio-Automator/manage.py", line 115, in torrents_add
    raise e
putiopy.ClientError: POST, https://upload.put.io/v2/files/upload, 401, Unauthorized, u"The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required."

**Comment by datashaman** [comment]
I'll have a look now, thanks for the report.

**Comment by datashaman** [comment]
I can't duplicate the error, it works fine if there's a torrent there already when I startup and also if I add one after it's started up.

Are you running the `torrents_watch` command when in the project folder? Give me more info about your config.

**Comment by krash1220** [comment]
I'm doing the same thing I've always done. I even tried uninstalling everything and reinstalling. I even thought it might be my token but I can upload a file to putio with curl -i -F file=@/path/to/the/file 'https://upload.put.io/v2/files/upload?oauth_token=xxxxxxxx' with the token I've always used. I'm on Linux Mint 18.1. I just don't understand it because I haven't changed anything. 

my config.py

import logging

DATABASE = 'application.db'
LOG_FILENAME = None
LOG_LEVEL = logging.WARNING
PUTIO_TOKEN = 'XXXXXXXX'
INCOMPLETE = '/TV/Incomplete'
TORRENTS = '/TV/Torrents'
DOWNLOADS = '/TV/Complete'

UPNP_PORT = 42000

**Comment by krash1220** [comment]
I'm getting the same errors for all commands except files_download, none of the other commands work. So I don't know if it's something that changed in Mint 18.1 or what but it has something to do with putio authorization. What version of linux do you use? I'm going to drop back to Mint 18 and see if that solves the problem but if it has anything to do with the changes at putio it won't matter. I really wish putio hadn't changed anything because everything was working fine before. This is really frustrating and disappointing.

**Comment by krash1220** [comment]
Also, it wouldn't be changes to putio.py would it. They have done changes to it 9 hours ago.
https://github.com/cenkalti/putio.py/commit/84f72b15617ec35bd72169fadae6db3c9fa6e555

**Comment by krash1220** [comment]
I dropped back to Linux Mint 18 but no luck. I was still getting the same error messages. I don't know what it is but for now I just won't be able to do anything but download torrents from putio.

**Comment by datashaman** [comment]
Ah-ha! Your comment about reinstalling made me do the same, and I'm seeing the same exception coming up now.

I'll let you know once I've solved it.

**Comment by krash1220** [comment]
Oh, thank goodness it's not just me. LOL Okay, thank you.

**Comment by datashaman** [comment]
You can change your requirements.txt to use the un-broken older version in the meantime (it seems to work for me, nothing extensively tested):

    putio.py<5.0.0

**Comment by krash1220** [comment]
No, didn't work for me. :-(

**Comment by datashaman** [comment]
Logged an issue https://github.com/cenkalti/putio.py/issues/31

**Comment by krash1220** [comment]
Sorry to bother you but I really miss this program. Still no luck? If an issue is closed will he still see your post?

**Comment by datashaman** [comment]
Hi there, no worries, I understand your pain. I'm busy negotiating a solution with Put.IO. Life and work are getting in the way.

I use a http://showrss.info/ feed directly in put.io, so I don't have an issue with adding torrents.

We'll find a way, it might take a week to get it working, but we'll figure something out.

**Comment by krash1220** [comment]
Okay, thanks for the update. I completely understand about life and work. I have faith you will get it fixed when you have the time.

**Comment by datashaman** [comment]
Would you be open to a change in architecture? Like using curl and some glue, bypassing the put.io client library?

**Comment by datashaman** [comment]
the fundamentals of this suite could be done with shell scripts, curl and a sprinkling of magic.

**Comment by datashaman** [comment]
could also fallback to using Put.IO API via requests package alone.

**Comment by krash1220** [comment]
Hey, I'm up for anything and almost always for a little magic. LOL I don't care how it's done as long as it works. I'm already a fan of shell scripts and curl is always installed. You do whatever is the easiest for you. All I really care about is having my torrents automatically uploaded after sickrage downloads them, the torrent files deleted after they've been uploaded, then downloaded for sickrage to  do the rest.

I don't have a clue about using Put.IO API via requests package alone. If that option is easier I say go for it.

**Comment by krash1220** [comment]
It's working again with the updated putio.py. Thank you both so much.

**Comment by datashaman** [comment]
Thanks, @cenkalti New release includes the updated putio.py https://github.com/datashaman/putio-automator/releases/tag/0.3.1
